// Generated by https://quicktype.io

import { api } from "./api";
import { Post } from "./posts";

export interface HomePosts {
    editorial:   HomeSection[];
    "section-1": HomeSection[];
    "section-2": HomeSection[];
    "section-3": HomeSection[];
    "section-4": HomeSection[];
}

export interface HomeSection {
    postId:  string;
    section: string;
    index:   number;
    id:      string;
    post:    Post;
}

export const getHomePosts = async (): Promise<HomePosts> => {
    const { data } = await api.get(`/posts/find/home`);
    return data as HomePosts;

}

export interface ResponseUpdateHomePost {
    postId:  string;
    section: string;
    index:   number;
    id:      string;
}
// Generated by https://quicktype.io

export interface RequestUpdateHomePost {
    postId: string;
}

export const updateHomePost = async (id: string, payload: RequestUpdateHomePost): Promise<ResponseUpdateHomePost> => {
    const { data } = await api.post(`/posts/update-home-post/${id}`, payload);
    return data as ResponseUpdateHomePost;
}