/* eslint-disable @typescript-eslint/no-explicit-any */
import { provinces } from "@/utils/mock";
import { api } from "./api";
export interface BodyRequest {
  PROVEEDOR: string;
  FECHAEMBAR: Date;
  CONTENEDOR: string;
  PLAZOPAGO: string;
  MONTO: number;
  ADELANTO: number;
  SALDO?: number;
  NOTA: string;
  ESTADO: number;
  USRINS: string;
  ESTINS: number;
  IDPRO: number;
  foto?: any;
}
export async function createShipment(body: BodyRequest): Promise<Shipment> {
  console.log({ body });
  const { data } = await api.post(`/embarques`, body, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });
  return data as Shipment;
}
export async function updateShipment(
  id: number,
  body: BodyRequest
): Promise<Shipment> {
  const { data } = await api.post(`/embarques/${id}`, body, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });
  return data as Shipment;
}
export async function updateStateShipment(id: number): Promise<Shipment> {
  const { data } = await api.post(`/embarque-estado/${id}`);
  return data as Shipment;
}
export async function deleteShipment(id: number): Promise<Shipment> {
  const { data } = await api.delete(`/embarques/${id}`);
  return data as Shipment;
}

export async function getShipments(): Promise<Shipment[]> {
  const { data } = await api.get(`/embarques`);
  return data as Shipment[];
}

export async function getProvincesShipment(): Promise<ProvincesShipment[]> {
  // const { data } = await api.get(`/provincias-embarques`);
  return provinces as ProvincesShipment[];
}

export async function getPaymentsByShipment(
  id: number
): Promise<PayShipment[]> {
  const { data } = await api.get(`/pago-embarque/${id}`);
  return data as PayShipment[];
}

export interface BodyRequestPay {
  NOPERACION?: string;
  FECHAPAGO?: Date;
  MONTO: number;
  USRINS: string;
  ESTINS: string;
  foto?: any;
}
export async function payShipment(
  id: number,
  body: BodyRequestPay
): Promise<Shipment> {
  const { data } = await api.post(`/pago-embarque/${id}`, body, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });
  return data as Shipment;
}

export async function updatePayShipment(
  id: number,
  body: BodyRequestPay
): Promise<Shipment> {
  const { data } = await api.post(`/actualizar-pago-embarque/${id}`, body, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });
  return data as Shipment;
}
export async function deletePayShipment(id: number): Promise<Shipment> {
  const { data } = await api.delete(`/pago-embarque/${id}`);
  return data as Shipment;
}

// Generated by https://quicktype.io

export interface Shipment {
  PROVEEDOR: string;
  FECHAEMBAR: string;
  CONTENEDOR: string;
  PLAZOPAGO: string;
  MONTO: number;
  ADELANTO: number;
  SALDO: number;
  NOTA: string;
  ESTADO: number;
  FECINS: string;
  USRINS: string;
  ESTINS: number;
  IDPRO: string;
  id: number;
  media: Media[];
  pagos: PayShipment[];
  media_full_url?: string;
}

export interface Media {
  id: number;
  model_type: string;
  model_id: string;
  uuid: string;
  collection_name: string;
  name: string;
  file_name: string;
  mime_type: string;
  disk: string;
  conversions_disk: string;
  size: string;
  manipulations: any[];
  custom_properties: any[];
  generated_conversions: any[];
  responsive_images: any[];
  order_column: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface ProvincesShipment {
  NOMPRO: string;
  id: number;
}

// Generated by https://quicktype.io

export interface PayShipment {
  IDEMBAR: string;
  FECHA: string;
  FOTO: null;
  FECHAPAGO: string;
  FECINS: string;
  USRINS: string;
  ESTINS: string;
  id: number;
  MONTO: number;
  media_full_url: string;
  media: Media[];
}
